//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enigma.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Enigma.Resources.AppResource", typeof(AppResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acuator ID.
        /// </summary>
        internal static string AcuatorIDText {
            get {
                return ResourceManager.GetString("AcuatorIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Notes.
        /// </summary>
        internal static string AddNotesButton {
            get {
                return ResourceManager.GetString("AddNotesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string AdvancedSettingsButton {
            get {
                return ResourceManager.GetString("AdvancedSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Calibrate.
        /// </summary>
        internal static string AutoCalibrateButton {
            get {
                return ResourceManager.GetString("AutoCalibrateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Calibrate.
        /// </summary>
        internal static string AutoCalibrateButton1 {
            get {
                return ResourceManager.GetString("AutoCalibrateButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCW End stops.
        /// </summary>
        internal static string CCWEndStopsText {
            get {
                return ResourceManager.GetString("CCWEndStopsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CW End stops.
        /// </summary>
        internal static string CWEndStopsText {
            get {
                return ResourceManager.GetString("CWEndStopsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Settings ID.
        /// </summary>
        internal static string FactorySettingsIDText {
            get {
                return ResourceManager.GetString("FactorySettingsIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Error Position.
        /// </summary>
        internal static string FirstErrorPositionText {
            get {
                return ResourceManager.GetString("FirstErrorPositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Settings.
        /// </summary>
        internal static string LoadSettingsButton {
            get {
                return ResourceManager.GetString("LoadSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Settings.
        /// </summary>
        internal static string LoadSettingsButton1 {
            get {
                return ResourceManager.GetString("LoadSettingsButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturing Date.
        /// </summary>
        internal static string ManufacturingDateText {
            get {
                return ResourceManager.GetString("ManufacturingDateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion Shift.
        /// </summary>
        internal static string MotionShiftText {
            get {
                return ResourceManager.GetString("MotionShiftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive Direction.
        /// </summary>
        internal static string PositiveDirectionText {
            get {
                return ResourceManager.GetString("PositiveDirectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power ups.
        /// </summary>
        internal static string PowerUpsText {
            get {
                return ResourceManager.GetString("PowerUpsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Up Wait Time.
        /// </summary>
        internal static string PowerUpWaitTimeText {
            get {
                return ResourceManager.GetString("PowerUpWaitTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        internal static string ResetAllButton {
            get {
                return ResourceManager.GetString("ResetAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset All.
        /// </summary>
        internal static string ResetAllButton1 {
            get {
                return ResourceManager.GetString("ResetAllButton1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        internal static string SpeedText {
            get {
                return ResourceManager.GetString("SpeedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string StandardSettingsButton {
            get {
                return ResourceManager.GetString("StandardSettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Calibration.
        /// </summary>
        internal static string StartCalibrationText {
            get {
                return ResourceManager.GetString("StartCalibrationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Position.
        /// </summary>
        internal static string StartPositionText {
            get {
                return ResourceManager.GetString("StartPositionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop_Mode.Mech..
        /// </summary>
        internal static string StopModeMech {
            get {
                return ResourceManager.GetString("StopModeMech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke Lengt.
        /// </summary>
        internal static string StrokeLengthText {
            get {
                return ResourceManager.GetString("StrokeLengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Running.
        /// </summary>
        internal static string TotalRunningText {
            get {
                return ResourceManager.GetString("TotalRunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Running Time.
        /// </summary>
        internal static string TotalRunningTimeText {
            get {
                return ResourceManager.GetString("TotalRunningTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Start Position.
        /// </summary>
        internal static string UseStartPositionText {
            get {
                return ResourceManager.GetString("UseStartPositionText", resourceCulture);
            }
        }
    }
}
